Name:           perl-Data-Compare-Plugins-JSON
Version:        1.04
Release:        1%{?dist}
Summary:        Plugin for Data::Compare to handle JSON, JSON::PP and JSON::XS boolean constants
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Data-Compare-Plugins-JSON/
Source0:        http://www.cpan.org/authors/id/D/DI/DIONYS/Data-Compare-Plugins-JSON-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008000
BuildRequires:  perl(Data::Compare)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
Requires:       perl(Data::Compare)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
JSON, JSON::PP and JSON::XS provides instances of JSON::PP::Boolean,
JSON::backportPP::Boolean, and JSON::XS::Boolean classes. It's JSON::true,
JSON::false, JSON::PP::true, JSON::PP::false, JSON::XS::true, and
JSON::XS::false. This plugin enables Data::Compare to compare this values.

%prep
%setup -q -n Data-Compare-Plugins-JSON-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Mar 07 2018 Your Name <wwright@nice.com> 1.04-1
- Specfile autogenerated by cpanspec 1.78.
