%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Crypt-OpenPGP
Version:        1.12
Release:        1%{?dist}
Summary:        Pure-Perl OpenPGP implementation
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Crypt-OpenPGP/
Source0:        http://www.cpan.org/authors/id/S/SR/SROMANOV/Crypt-OpenPGP-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Alt::Crypt::RSA::BigInt)
BuildRequires:  perl(Compress::Zlib)
BuildRequires:  perl(Crypt::Blowfish)
BuildRequires:  perl(Crypt::CAST5_PP)
BuildRequires:  perl(Crypt::DES_EDE3)
BuildRequires:  perl(Crypt::DSA)
BuildRequires:  perl(Crypt::IDEA)
BuildRequires:  perl(Crypt::Rijndael)
BuildRequires:  perl(Crypt::RIPEMD160)
BuildRequires:  perl(Crypt::Twofish)
BuildRequires:  perl(Data::Buffer) >= 0.04
BuildRequires:  perl(Digest::MD5)
BuildRequires:  perl(Digest::SHA)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::HomeDir)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Math::BigInt)
BuildRequires:  perl(MIME::Base64)
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(URI::Escape)
BuildRequires:  perl(Bytes::Random::Secure)
Requires:       perl(Alt::Crypt::RSA::BigInt)
Requires:       perl(Compress::Zlib)
Requires:       perl(Crypt::Blowfish)
Requires:       perl(Crypt::CAST5_PP)
Requires:       perl(Crypt::DES_EDE3)
Requires:       perl(Crypt::DSA)
Requires:       perl(Crypt::IDEA)
Requires:       perl(Crypt::Rijndael)
Requires:       perl(Crypt::RIPEMD160)
Requires:       perl(Crypt::Twofish)
Requires:       perl(Data::Buffer) >= 0.04
Requires:       perl(Digest::MD5)
Requires:       perl(Digest::SHA)
Requires:       perl(File::HomeDir)
Requires:       perl(LWP::UserAgent)
Requires:       perl(Math::BigInt)
Requires:       perl(MIME::Base64)
Requires:       perl(URI::Escape)
Requires:       perl(Bytes::Random::Secure)

%description
Crypt::OpenPGP is a pure-Perl implementation of the OpenPGP standard[1]. In
addition to support for the standard itself, Crypt::OpenPGP claims
compatibility with many other PGP implementations, both those that support
the standard and those that preceded it.

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0 

%prep
%setup -q -n Crypt-OpenPGP-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes CREDITS dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Mar 07 2018 Your Name <wwright@nice.com> 1.12-1
- Specfile autogenerated by cpanspec 1.78.
