%{!?perl_vendorarch: %define perl_vendorarch %(eval "`%{__perl} -V:installvendorarch`"; echo $installvendorarch)}

Name:           perl-Term-Size
Version:        0.207
Release:        1%{?dist}
Summary:        Retrieve terminal size (Unix version)
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Term-Size/
Source0:        http://www.planet-elektronik.de/CPAN//authors/id/F/FE/FERREIRA/Term-Size-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
Requires:       perl(Test::More)

%description
THIS IS AN UNOFFICIAL PATCH AGAINST Term-Size 0.2 DISTRIBUTION FOUND ON
CPAN (http://search.cpan.org/~timpx/Term-Size-0.2/).  IT IS UNOFFICIAL IN
THE SENSE THAT THE AUTHOR Tim Goodwin  HASN'T APPROVED IT (YET, I HOPE).
BECAUSE OF THIS, THIS  DISTRIBUTION IS NOT INDEXED AND AVAILABLE VIA cpan
OR cpanp  SHELLS UNLESS YOU EXPLICITLY SAY  "install FERREIRA/Term-Size-
0.203.tar.gz".

THIS IS UNDELICATE? I THINK IT IS IN A CERTAIN SENSE. BUT IT IS A WAY TO
UNFREEZE THE CURRENT DISTRIBUTION STATUS. IF TIM DISAPPROVES, I WILL REMOVE
THIS DISTRIBUTION RIGHT AWAY. IF HE APPROVES, I WILL REMOVE THIS
DISTRIBUTION RIGHT AWAY AND WORK OUT (AFTER BEEN GIVEN MAINTAINERSHIP
STATUS) A DISTRIBUTION WITHOUT THIS NOTE AND WHICH INDEXES CORRECTLY.

%prep
%setup -q -n Term-Size-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
%{__perl} -pi -e 's/^\tLD_RUN_PATH=[^\s]+\s*/\t/' Makefile
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes Copyright README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Term*
%{_mandir}/man3/*

%changelog
* Wed Mar 07 2018 Your Name <wwright@nice.com> 0.207-1
- Specfile autogenerated by cpanspec 1.78.
