%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-Test-MockModule
Version:        0.13
Release:        1%{?dist}
Summary:        Override subroutines in a module for unit testing
License:        GPL+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Test-MockModule/
Source0:        http://www.planet-elektronik.de/CPAN//authors/id/G/GF/GFRANKS/Test-MockModule-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(Carp)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(SUPER)
BuildRequires:  perl(Test::More) >= 0.88
Requires:       perl(Carp)
Requires:       perl(Scalar::Util)
Requires:       perl(SUPER)

%description
Test::MockModule lets you temporarily redefine subroutines in other
packages for the purposes of unit testing.

%prep
%setup -q -n Test-MockModule-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Mar 07 2018 Your Name <wwright@nice.com> 0.13-1
- Specfile autogenerated by cpanspec 1.78.
