Name:           perl-Env-Path
Version:        0.19
Release:        1%{?dist}
Summary:        Advanced operations on path variables
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Env-Path/
Source0:        http://www.cpan.org/authors/id/D/DS/DSB/Env-Path-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Env::Path presents an object-oriented interface to path variables, defined
as that subclass of environment variables which name an ordered list of
filesystem elements separated by a platform-standard separator (typically
':' on UNIX and ';' on Windows).

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0 

%prep
%setup -q -n Env-Path-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes envpath README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Mar 05 2018 Your Name <wwright@nice.com> 0.19-1
- Specfile autogenerated by cpanspec 1.78.



