%{!?perl_vendorlib: %define perl_vendorlib %(eval "`%{__perl} -V:installvendorlib`"; echo $installvendorlib)}

Name:           perl-jmx4perl
Version:        1.12
Release:        1%{?dist}
Summary:        jmx4perl Perl module
License:        GPL+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/jmx4perl/
Source0:        http://www.cpan.org/authors/id/R/RO/ROLAND/jmx4perl-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Archive::Zip)
BuildRequires:  perl(base)
BuildRequires:  perl(Carp)
BuildRequires:  perl(Config::General) >= 2.34
BuildRequires:  perl(Crypt::Blowfish_PP)
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(Digest::MD5)
BuildRequires:  perl(Digest::SHA1)
BuildRequires:  perl(File::SearchPath)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(Getopt::Long)
BuildRequires:  perl(IO::Socket::Multicast)
BuildRequires:  perl(JSON) >= 2.12
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Module::Find)
BuildRequires:  perl(Monitoring::Plugin) >= 0.37
BuildRequires:  perl(Pod::Usage)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Sys::SigAction)
BuildRequires:  perl(Term::Clui)
BuildRequires:  perl(Term::ProgressBar)
BuildRequires:  perl(Term::ShellUI)
BuildRequires:  perl(Term::Size) >= 0.207
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Text::ParseWords)
BuildRequires:  perl(Time::HiRes)
BuildRequires:  perl(URI) >= 1.35
BuildRequires:  perl(XML::LibXML)
BuildRequires:  perl(XML::Twig)
Requires:       perl(Archive::Zip)
Requires:       perl(base)
Requires:       perl(Carp)
Requires:       perl(Config::General) >= 2.34
Requires:       perl(Crypt::Blowfish_PP)
Requires:       perl(Data::Dumper)
Requires:       perl(Digest::MD5)
Requires:       perl(Digest::SHA1)
Requires:       perl(File::SearchPath)
Requires:       perl(File::Temp)
Requires:       perl(Getopt::Long)
Requires:       perl(IO::Socket::Multicast)
Requires:       perl(JSON) >= 2.12
Requires:       perl(LWP::UserAgent)
Requires:       perl(Module::Find)
Requires:       perl(Monitoring::Plugin) >= 0.37
Requires:       perl(Pod::Usage)
Requires:       perl(Scalar::Util)
Requires:       perl(Sys::SigAction)
Requires:       perl(Term::Clui)
Requires:       perl(Term::ProgressBar)
Requires:       perl(Term::ShellUI)
Requires:       perl(Term::Size) >= 0.207
Requires:       perl(Text::ParseWords)
Requires:       perl(Time::HiRes)
Requires:       perl(URI) >= 1.35
Requires:       perl(XML::LibXML)
Requires:       perl(XML::Twig)

%description
Jmx4Perl provides an alternate way for accessing Java JEE Server management
interfaces which are based on JMX (Java Management Extensions). It is an
agent based approach, where a small Java Webapplication deployed on the
application server provides an HTTP/JSON based access to JMX MBeans
registered within the application server.

%define _unpackaged_files_terminate_build 0
%define _missing_doc_files_terminate_build 0 

%prep
%setup -q -n jmx4perl-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc CHANGES config docker examples it LICENSE META.json README scripts
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Mar 07 2018 Your Name <wwright@nice.com> 1.12-1
- Specfile autogenerated by cpanspec 1.78.
