%{!?perl_vendorarch: %define perl_vendorarch %(eval "`%{__perl} -V:installvendorarch`"; echo $installvendorarch)}

Name:           perl-Config-General
Version:        2.63
Release:        1%{?dist}
Summary:        Generic Config Module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Config-General/
Source0:        http://www.planet-elektronik.de/CPAN//authors/id/T/TL/TLINDEN/Config-General-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Glob)
BuildRequires:  perl(FileHandle)
BuildRequires:  perl(File::Spec::Functions)
BuildRequires:  perl(IO::File)
Requires:       perl(File::Glob)
Requires:       perl(FileHandle)
Requires:       perl(File::Spec::Functions)
Requires:       perl(IO::File)

%description
This module opens a config file and parses its contents for you. The new
method requires one parameter which needs to be a filename. The method
getall returns a hash which contains all options and its associated values
of your config file.

%prep
%setup -q -n Config-General-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
%{__perl} -pi -e 's/^\tLD_RUN_PATH=[^\s]+\s*/\t/' Makefile
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check || :
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changelog META.json README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Config*
%{_mandir}/man3/*

%changelog
* Wed Mar 07 2018 Your Name <wwright@nice.com> 2.63-1
- Specfile autogenerated by cpanspec 1.78.
